### ISSUE TITLE
Hubot ROCKETCHAT_ROOM behaviour changed between RC 0.27 and 0.29

### ISSUE THREAD

**Issue by rebeld** [RocketChat/hubot-rocketchat#115]
Rocket Chat Version: 0.29.

With RC 0.27, hubot would connect properly, with 0.29 it wouldn't.

The hubot error:

```[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: Servo
[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO Connecting To: nn.nn.nn.nn:3000
[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO Successfully connected!
[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO 'GENERAL'
[Wed May 04 2016 15:55:27 GMT+0000 (UTC)] INFO Logging In
[Wed May 04 2016 15:55:28 GMT+0000 (UTC)] INFO Successfully Logged In
[Wed May 04 2016 15:55:28 GMT+0000 (UTC)] INFO Looking up Room ID for: 'GENERAL'
[Wed May 04 2016 15:55:28 GMT+0000 (UTC)] ERROR Unable to get room id: {"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"} Reason: Internal server error
[Wed May 04 2016 15:55:28 GMT+0000 (UTC)] ERROR {"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}
[Wed May 04 2016 15:55:28 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.```

The RC error:

```Exception while invoking method 'getRoomIdByNameOrId' TypeError: Cannot read property 'usernames' of undefined
    at [object Object].Meteor.methods.getRoomIdByNameOrId (server/methods/getRoomIdByNameOrId.coffee:6:10)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)```

Our configuration hasn't changed in some time. We have RC running with a connect hubot deployed with docker. The environment vars had `- ROCKETCHAT_ROOM='GENERAL'` though our room with the _id of 'GENERAL' is not named 'General'. Commenting out that env var allows hubot to connect again. 

```[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: Servo
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using GENERAL
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Connecting To: nn.nn.nn.nn:3000
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Successfully connected!
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO GENERAL
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Logging In
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Successfully Logged In
[Wed May 04 2016 19:27:32 GMT+0000 (UTC)] INFO Looking up Room ID for: GENERAL
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Joining Room: GENERAL
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO All rooms joined.
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Subscribing to Room: GENERAL
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO All subscriptions ready.
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Successfully subscribed to room: GENERAL
[Wed May 04 2016 19:27:33 GMT+0000 (UTC)] INFO Setting up reactive message list...```

**Comment by geekgonecrazy** [comment]
Here is the link for some context: https://demo.rocket.chat/channel/support?msg=JjJAmhRPmqpj8DXoR
Not sure why the usernames property doesn't exist on room.  But this is probably where we need to start to get rid of that error, then see where we stand.

**Comment by tennix** [comment]
I've updated today and got the same issue. And there's no way to rollback as there's only latest tag on DockerHub. So could you please add a tag for each release version when pushing your images to DockerHub? And also please fix this issue asap, thanks

**Comment by tennix** [comment]
Simply remove `ROCKETCHAT_ROOM` env setting in docker-compose make hubot work again

**Comment by geekgonecrazy** [comment]
We're now tagging each release of the docker images.  As well as this should be resolved with the newest version of Rocket.Chat 0.37.0 and adapter version v1.0.3
