### ISSUE TITLE
Error when I don't need any EXTERNAL_SCRIPTS

### ISSUE THREAD

**Issue by dannyZhou** [RocketChat/hubot-rocketchat#198]
Sometimes I don't need any `EXTERNAL_SCRIPTS` so I empty `EXTERNAL_SCRIPTS` when I set `docker-compose.yml` this is an example. 

```docker
version: '2.1'
services:
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    environment:
      - ROCKETCHAT_URL=${ROCKETCHAT_URL:-http://localhost:3000}
      - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM:-general}
      - ROCKETCHAT_USER=${ROCKETCHAT_USER:-bot}
      - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD:-botpassword}
      - BOT_NAME=${BOT_NAME:-bot}
      - EXTERNAL_SCRIPTS=
      - HUBOT_JENKINS_URL=${HUBOT_JENKINS_URL:-http://localhost:8090}
      - HUBOT_JENKINS_AUTH=${HUBOT_JENKINS_AUTH}
    volumes:
      - ./scripts:/home/hubot/scripts

```

I run `docker-compose up`

Error is: 

```
hubot_1  | 
hubot_1  | Your hubot-scripts.json is empty, so you just need to remove it.
hubot_1  | [Fri Feb 03 2017 01:21:05 GMT+0000 (UTC)] ERROR Error loading scripts from npm package - AssertionError: missing path
hubot_1  |   at Module.require (module.js:363:3)
hubot_1  |   at require (module.js:384:17)
hubot_1  |   at Robot.loadExternalScripts (/home/hubot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:27)
hubot_1  |   at /home/hubot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
hubot_1  |   at fs.js:334:14
hubot_1  |   at FSReqWrap.oncomplete (fs.js:95:15)
hubot_1  | 
myhubot_hubot_1 exited with code 1

```

**Comment by rrLucho** [comment]
Did you find a solution for this?

I'm running into the same issue

**Comment by agepilar** [comment]
I'm also running into the same issue. Is it possible to do simply something like
` - EXTERNAL_SCRIPTS=false
`
or 
` - EXTERNAL_SCRIPTS=none
`
If starting docker-compose.yml without 
` - EXTERNAL_SCRIPTS=
`
hubot install automatically some hubot scripts like hubot-help etc.
