### ISSUE TITLE
HuBot cannot reply to the same room after receiving message in v1.0.9 works in 1.0.8

### ISSUE THREAD

**Issue by mhou1981** [RocketChat/hubot-rocketchat#227]
Rocket.Chat Version:  0.57.2
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.2

HuBot cannot reply to the same room after receiving message.  Error as follows:
```
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message received with ID id
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message receive callback id RsAqfEDLkJJraKuyc ts Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO [Incoming] mhou: rocketchat help
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Looking up Room Name for: 54cWy9hBgv2i98Zb7yK7LxPZfeFKv8XZpm
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Message sent to hubot brain.
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Sending Message To Room: undefined
Jul 17 15:13:33 Ubuntu docker[22944]: [Mon Jul 17 2017 15:13:33 GMT-0700 (PDT)] INFO Looking up Room ID for: undefined
```

Rocket Chat error message:
```
Jul 17 15:06:50 Ubuntu snap[2292]: Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: 54cWy9hBgv2i98Zb7yK7LxPZfeFKv8XZpm
Jul 17 15:06:50 Ubuntu snap[2292]: Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
Jul 17 15:06:50 Ubuntu snap[2292]: Meteor ➔ method getRoomIdByNameOrId -> userId: yK7LxPZfeFKv8XZpm , arguments:  { '0': null }
Jul 17 15:06:50 Ubuntu snap[2292]: Exception while invoking method 'getRoomIdByNameOrId' Error: Match error: Expected string, got null
Jul 17 15:06:50 Ubuntu snap[2292]:   at exports.check (packages/check.js:57:15)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].Meteor.methods.getRoomIdByNameOrId (/snap/rocketchat-server/829/programs/server/app/app.js:6821:3)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/829/programs/server/packages/rocketchat_lib.js:1028:26)
Jul 17 15:06:50 Ubuntu snap[2292]:   at maybeAuditArgumentChecks (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:1823:12)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:905:20
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:904:41
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:903:46
Jul 17 15:06:50 Ubuntu snap[2292]:   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/829/programs/server/packages/ddp-server.js:876:21)
Jul 17 15:06:50 Ubuntu snap[2292]:   at /snap/rocketchat-server/829/programs/server/packages/ddp-server.js:755:85
Jul 17 15:06:50 Ubuntu snap[2292]: Sanitized and reported to the client as: Match failed [400]
Jul 17 15:06:50 Ubuntu snap[2292]: undefined undefined
```

In our production server v1.0.8 works without any issue.  Local test uses v1.0.9 and not working.  I have changed the docker script to use 
```
/usr/bin/docker run rocketchat/hubot-rocketchat:1.0.8
```

it fails when using just rocketchat/hubot-rocketchat

**Comment by d89** [comment]
Same here, also with Rocket.Chat 0.57.2. Going back to hubot 1.0.8 did the trick. Note that every other kind of message worked fine, just "direct responses" to users did not.

**Comment by xurizaemon** [comment]
Ah, I see this also.

    # export RESPOND_TO_DM=true
    export ROCKETCHAT_ROOM=''
    export LISTEN_ON_ALL_PUBLIC=true

I see -

    INFO [Incoming] myusername: ping
    INFO Checking to see if method: getRoomNameById exists
    INFO Looking up Room Name for: EggHG3uDCAFk ...
    INFO setting roomName: undefined
    INFO Message sent to hubot brain.
    INFO Sending Message To Room: undefined
    INFO Looking up Room ID for: undefined

Hubot hears my commands but the response is directed to (undefined) so not visible to the interacting user.

Since this is a fresh hubot / 🚀 install I was not 100% that it's *not* my misconfiguration ... I'm happy to discuss in https://demo.rocket.chat/channel/hubot and see if I've discovered a problem. However seeing these reports in this issue, I guess it's a proper bug.

I think it relates to this recent change? #229 That's where we end up looking for a roomname by ID and getting `undefined` back.

**Comment by JigSawFr** [comment]
Same problem on our side

**Comment by Sing-Li** [comment]
Note to make sure you set `RESPOND_TO_DM=true`

**Comment by mhou1981** [comment]
```
RESPOND_TO_DM=true 
```
Has already been set.

**Comment by timkinnane** [comment]
This looks like an outdated or specific config issue that I'll assume is now resolved. If it's still unresolved please comment and I'll reopen.
