### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jarro2783** [RocketChat/hubot-rocketchat#264]
After fixing the issue in #263, I think there is still a memory leak. After running in a relatively active rocketchat instance, the bot dies after about a day, after using a lot of memory, and a CPU profile shows that it is spending most of its time garbage collecting.

I took some heap snapshots and tried to find objects that didn't look like they should have been hanging around.

It's hard for me to work out exactly what's going on, but `rocketchat_driver.coffee` line 162 looks a bit suspicious. It is calling `@messages.reactiveQuery` every time it gets a message. This calls Asteroid's `Set.filter` function, which attaches two event handlers `"put"`, and `"del"` to the `Set`, which I suspect it never cleans up.

**Comment by geekgonecrazy** [comment]
Definitely had not been optimized for memory.  Might also be LRU..  but yeah I'm guessing we're defining variables and leaving them hanging

**Comment by vikaskedia** [comment]
I am facing same problem. Upgrading to node 8 might solve the problem. It is supposed to be much better than node 4.

When trying to upgrade to node 8 I am getting the following error

![image](https://user-images.githubusercontent.com/6703876/36343343-d0e16274-13bf-11e8-9cb4-8406d7df2229.png)


@geekgonecrazy  please help

**Comment by jarro2783** [comment]
I'm using Node 9 and it seems to work fine.

**Comment by vikaskedia** [comment]
@jarro2783 can you show me the changes you did to Dockerfile to make it run on node 9 ?

**Comment by jarro2783** [comment]
I'm not using the `Dockerfile` in the repository. I just added it to a minimal Node package with `hubot` and ran `npm install`.

**Comment by jarro2783** [comment]
I'm happy to help, I'll be in contact.

**Comment by timkinnane** [comment]
Please test this with current develop branch. It's working with Hubot v3 and we've put up a demo here: https://github.com/RocketChat/hubot-rocketchat-boilerplate

Most of the code is rewritten and using updated dependencies so hopefully we got rid of the memory leaks along the way.

**Comment by jarro2783** [comment]
Will do. I did mean to contact you on open.rocket.chat, but I've had a lot of other more important things to do.

**Comment by jarro2783** [comment]
So far the only problem I've had is that `robot.messageRoom` fails with:
```
[Wed Apr 18 2018 15:25:33 GMT+1000 (AEST)] ERROR while invoking error handler: TypeError: Cannot read property 'roomID' of undefined
TypeError: Cannot read property 'roomID' of undefined
  at strings.map (/home/jarryd/src/freelancer/chatbot/node_modules/hubot-rocketchat/index.js:155:25)
  at Array.map (<anonymous>:null:null)
  at Robot.send (/home/jarryd/src/freelancer/chatbot/node_modules/hubot-rocketchat/index.js:154:20)
  at Robot.messageRoom (/home/jarryd/src/freelancer/chatbot/node_modules/hubot/src/robot.js:608:23)
  at robot.error (/home/jarryd/src/freelancer/chatbot/src/scripts/error-handler.js:17:13)
```
