### ISSUE TITLE
robot.adapter.callMethod is not a function

### ISSUE THREAD

**Issue by ulope** [RocketChat/hubot-rocketchat#281]
I'm trying to implement a bot that updates messages as suggested in #126. 

However, something seems to have changed since then since I'm unable to use `robot.adapter.callMethod` as it results in an error message in the log: `TypeError: robot.adapter.callMethod is not a function`

RocketChat version: 0.64.0

Full test script:
```javascript
module.exports = function(robot) {
    robot.respond(/test/i, function(msg) {
        robot.adapter.callMethod(
            'updateMessage', 
            {
                _id: msg.message.id,
                rid: msg.message.room,
                msg: 'bla'
            }
        );
    });
};
```

Relevant log lines:
```
Loaded test.js
Exception in callback of async function: TypeError: robot.adapter.callMethod is not a function
    at /hubot/scripts/test.js:3:23
    at runWithEnvironment (packages/meteor.js:1238:24)
    at packages/meteor.js:1251:14
    at runWithEnvironment (packages/meteor.js:1238:24)
```

**Comment by ulope** [comment]
Apparently the problem is that the RC internal hubot doesn't use this adapter but rather another less functional one...

I'll close this issue and have opened RocketChat/Rocket.Chat#10646 instead
