### ISSUE TITLE
yo error when compiling Dockerfile

### ISSUE THREAD

**Issue by boyobejamin** [RocketChat/hubot-rocketchat#308]
Hey there, first time hubot user here. When creating my own docker container based off the Dockerfile in the repo, I get the following error message. I was able to get past it by changing the Dockerfile from using "node:4.8.3" to "node:latest". Not sure if that's the smart play but wanted to forward it along.

------------------------------------------------------------------------------------

npm info install yo@2.0.5
npm info postinstall yo@2.0.5

> yo@2.0.5 postinstall /usr/local/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
coffee-script@1.12.7 /usr/local/lib/node_modules/coffee-script

generator-hubot@0.4.0 /usr/local/lib/node_modules/generator-hubot
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── yosay@0.3.0 (string-length@0.1.2, ansi-regex@0.2.1, ansi-styles@1.1.0, pad-component@0.0.1, word-wrap@0.1.3, minimist@0.2.0, strip-ansi@0.2.2, chalk@0.4.0, taketalk@0.1.1)
├── npm-name@1.2.0 (log-symbols@1.0.2, registry-url@3.1.0, got@5.7.1, meow@3.7.0)
└── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.4.0, isbinaryfile@2.0.4, async@0.9.2, underscore.string@2.4.0, mime@1.6.0, text-table@0.2.0, class-extend@0.1.2, lodash@2.4.2, debug@1.0.5, nopt@3.0.6, cross-spawn@0.2.9, run-async@0.1.0, shelljs@0.3.0, iconv-lite@0.4.24, mkdirp@0.5.1, glob@4.5.3, rimraf@2.6.3, file-utils@0.2.2, findup-sync@0.1.3, github-username@1.1.1, download@1.0.7, gruntfile-editor@0.2.0, cheerio@0.17.0, request@2.88.0, inquirer@0.7.3, grouped-queue@0.3.3)

yo@2.0.5 /usr/local/lib/node_modules/yo
├── titleize@1.0.1
├── cli-list@0.2.0
├── figures@2.0.0 (escape-string-regexp@1.0.5)
├── humanize-string@1.0.2 (decamelize@1.2.0)
├── user-home@2.0.0 (os-homedir@1.0.2)
├── opn@5.4.0 (is-wsl@1.1.0)
├── string-length@2.0.0 (astral-regex@1.0.0, strip-ansi@4.0.0)
├── sort-on@3.0.0 (arrify@1.0.1, dot-prop@4.2.0)
├── yeoman-character@1.1.0 (supports-color@3.2.3)
├── configstore@3.1.2 (xdg-basedir@3.0.0, graceful-fs@4.1.15, make-dir@1.3.0, dot-prop@4.2.0, unique-string@1.0.0, write-file-atomic@2.3.0)
├── cross-spawn@6.0.5 (path-key@2.0.1, nice-try@1.0.5, semver@5.6.0, shebang-command@1.2.0, which@1.3.1)
├── parse-help@1.0.0 (execall@1.0.0)
├── root-check@1.0.0 (downgrade-root@1.2.2, sudo-block@1.2.0)
├── chalk@2.4.2 (escape-string-regexp@1.0.5, supports-color@5.5.0, ansi-styles@3.2.1)
├── global-tunnel-ng@2.7.1 (encodeurl@1.0.2, tunnel@0.0.6, npm-conf@1.1.3)
├── yosay@2.0.2 (strip-ansi@3.0.1, ansi-regex@2.1.1, pad-component@0.0.1, cli-boxes@1.0.0, chalk@1.1.3, string-width@2.1.1, taketalk@1.0.0, ansi-styles@3.2.1, wrap-ansi@2.1.0)
├── package-json@5.0.0 (semver@5.6.0, registry-url@3.1.0, registry-auth-token@3.3.2)
├── npm-keyword@5.0.0 (registry-url@3.1.0, got@7.1.0)
├── read-pkg-up@4.0.0 (read-pkg@3.0.0, find-up@3.0.0)
├── fullname@3.3.0 (filter-obj@1.1.0, p-try@1.0.0, mem@1.1.0, rc@1.2.8, p-any@1.1.0, execa@0.6.3, passwd-user@2.1.0)
├── got@8.3.2 (lowercase-keys@1.0.1, timed-out@4.0.1, duplexer3@0.1.4, decompress-response@3.3.0, p-cancelable@0.4.1, pify@3.0.0, mimic-response@1.0.1, is-retry-allowed@1.1.0, url-to-options@1.0.1, get-stream@3.0.0, safe-buffer@5.1.2, @sindresorhus/is@0.7.0, p-timeout@2.0.1, url-parse-lax@3.0.0, cacheable-request@2.1.4, isurl@1.0.0, into-stream@3.1.0)
├── meow@3.7.0 (decamelize@1.2.0, trim-newlines@1.0.0, map-obj@1.0.1, object-assign@4.1.1, minimist@1.2.0, camelcase-keys@2.1.0, loud-rejection@1.6.0, normalize-package-data@2.4.0, redent@1.0.0, read-pkg-up@1.0.1)
├── update-notifier@2.5.0 (is-npm@1.0.0, import-lazy@2.1.0, xdg-basedir@3.0.0, semver-diff@2.1.0, is-ci@1.2.1, is-installed-globally@0.1.0, latest-version@3.1.0, boxen@1.3.0)
├── async@2.6.1
├── yeoman-environment@2.3.4 (escape-string-regexp@1.0.5, untildify@3.0.3, grouped-queue@0.3.3, log-symbols@2.2.0, text-table@0.2.0, strip-ansi@4.0.0, is-scoped@1.0.0, debug@3.2.6, diff@3.5.0, mem-fs@1.1.3, globby@8.0.2)
├── tabtab@1.3.2 (object-assign@4.1.1, minimist@1.2.0, debug@2.6.9, mkdirp@0.5.1, npmlog@2.0.4, inquirer@1.2.3)
├── yeoman-doctor@3.0.3 (object-values@1.0.0, log-symbols@2.2.0, semver@5.6.0, each-async@1.1.1, ansi-styles@3.2.1, latest-version@3.1.0, bin-version-check@3.0.0, twig@1.13.0)
├── lodash@4.17.11
├── inquirer@6.2.1 (ansi-escapes@3.1.0, cli-width@2.2.0, through@2.3.8, mute-stream@0.0.7, strip-ansi@5.0.0, run-async@2.3.0, string-width@2.1.1, cli-cursor@2.1.0, external-editor@3.0.3, rxjs@6.3.3)
└── insight@0.10.1 (lodash.debounce@4.0.8, uuid@3.3.2, os-name@2.0.1, tough-cookie@2.5.0, conf@1.4.0, request@2.88.0, inquirer@5.2.0)
npm info ok 
Removing intermediate container d44f486c4fb2
 ---> f8e0ef60e175
Step 4/16 : USER hubot
 ---> Running in de557f1ea8b9
Removing intermediate container de557f1ea8b9
 ---> 085c6af7a8c7
Step 5/16 : WORKDIR /home/hubot
 ---> Running in b9cfe92a8280
Removing intermediate container b9cfe92a8280
 ---> 25e1d8aee32e
Step 6/16 : ENV BOT_NAME "rocketbot"
 ---> Running in 2dc24a731429
Removing intermediate container 2dc24a731429
 ---> 341a40a7355b
Step 7/16 : ENV BOT_OWNER "No owner specified"
 ---> Running in e42dc8557d06
Removing intermediate container e42dc8557d06
 ---> 0ae47fdd3c2b
Step 8/16 : ENV BOT_DESC "Hubot with rocketbot adapter"
 ---> Running in 1b33c2e7ea0d
Removing intermediate container 1b33c2e7ea0d
 ---> 5fd4f81595fe
Step 9/16 : ENV EXTERNAL_SCRIPTS=hubot-diagnostics,hubot-help,hubot-google-images,hubot-google-translate,hubot-pugme,hubot-maps,hubot-rules,hubot-shipit
 ---> Running in 1d8cde4cdd88
Removing intermediate container 1d8cde4cdd88
 ---> 181405ea8d3a
Step 10/16 : RUN yo hubot --owner="$BOT_OWNER" --name="$BOT_NAME" --description="$BOT_DESC" --defaults && 	sed -i /heroku/d ./external-scripts.json && 	sed -i /redis-brain/d ./external-scripts.json && 	npm install hubot-scripts
 ---> Running in f0275a6d7bf3
/usr/local/lib/node_modules/yo/lib/cli.js:204
    insight.track(...firstCmd.args.slice(0, 2));
                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
The command '/bin/sh -c yo hubot --owner="$BOT_OWNER" --name="$BOT_NAME" --description="$BOT_DESC" --defaults && 	sed -i /heroku/d ./external-scripts.json && 	sed -i /redis-brain/d ./external-scripts.json && 	npm install hubot-scripts' returned a non-zero code: 1

**Comment by xlogin** [comment]
ME TOOOOOO!  Is This project  now no one to maintain inside？
